name: breaking_bapp
description: Sample app for the Infinite Scroll Pagination package.
publish_to: none
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cached_network_image: ^3.0.0
  flutter:
    sdk: flutter
  http: ^0.13.3
  infinite_scroll_pagination:
    path: ../
  rxdart: ^0.27.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true