name: infinite_scroll_pagination
description: Lazily load and display pages of items as the user scrolls down your screen.
version: 4.0.0
homepage: https://github.com/EdsonBueno/infinite_scroll_pagination

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.22.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.4.1
  sliver_tools: ^0.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.3
  test: ^1.16.5
