name: infinite_scroll_pagination
description: Lazily load and display pages of items as the user scrolls down your screen.
version: 3.0.1+1
homepage: https://github.com/EdsonBueno/infinite_scroll_pagination

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.22.0'

dependencies:
  flutter:
    sdk: flutter
  sliver_tools: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  test: ^1.16.5
